import { BrasaPointsRegistration } from "./types";

export const SAMPLE_REGISTRATIONS: BrasaPointsRegistration[] = [
  {
    fullName: "Ana Diaz",
    email: "ana@example.com",
    phone: "+57 300 123 4567",
    country: "Colombia",
    city: "Medellín",
    favoriteBrasalandLocation: "Brasaland El Poblado",
    dietaryPreferences: ["No restrictions"],
    howDidYouFindUs: "Social media",
    dateOfBirth: "1995-05-10",
    acceptsProgramTerms: true,
    wantsEmailOffers: true,
    createdAt: "2026-04-10T12:00:00.000Z",
  },
  {
    fullName: "Miguel Fernandez",
    email: "miguel@example.com",
    phone: "+57 301 987 2456",
    country: "Colombia",
    city: "Bogotá",
    favoriteBrasalandLocation: "Brasaland Chapinero",
    dietaryPreferences: ["Gluten-free"],
    howDidYouFindUs: "Recommendation",
    dateOfBirth: "1989-01-18",
    acceptsProgramTerms: true,
    wantsEmailOffers: false,
    createdAt: "2026-04-11T09:30:00.000Z",
  },
  {
    fullName: "Lucia Salazar",
    email: "lucia@example.com",
    phone: "+57 315 765 4321",
    country: "Colombia",
    city: "Cali",
    favoriteBrasalandLocation: "Brasaland Granada",
    dietaryPreferences: ["Vegetarian"],
    howDidYouFindUs: "Internet search",
    dateOfBirth: "1998-08-22",
    acceptsProgramTerms: true,
    wantsEmailOffers: true,
    createdAt: "2026-04-12T14:15:00.000Z",
  },
  {
    fullName: "Beth Carter",
    email: "beth@example.com",
    phone: "+1 305 123 4567",
    country: "United States",
    city: "Miami",
    favoriteBrasalandLocation: "Brasaland Brickell",
    dietaryPreferences: ["No restrictions", "Other"],
    howDidYouFindUs: "Walked by",
    dateOfBirth: "1990-08-03",
    acceptsProgramTerms: true,
    wantsEmailOffers: false,
    createdAt: "2026-04-13T11:05:00.000Z",
  },
  {
    fullName: "Marcus Lewis",
    email: "marcus@example.com",
    phone: "+1 407 444 2200",
    country: "United States",
    city: "Orlando",
    favoriteBrasalandLocation: "Brasaland Downtown",
    dietaryPreferences: ["No restrictions"],
    howDidYouFindUs: "Social media",
    dateOfBirth: "1992-04-06",
    acceptsProgramTerms: true,
    wantsEmailOffers: true,
    createdAt: "2026-04-14T16:45:00.000Z",
  },
  {
    fullName: "Daniela Torres",
    email: "daniela@example.com",
    phone: "+57 304 882 1901",
    country: "Colombia",
    city: "Medellín",
    favoriteBrasalandLocation: "Brasaland Laureles",
    dietaryPreferences: ["No restrictions"],
    howDidYouFindUs: "Recommendation",
    dateOfBirth: "1997-12-01",
    acceptsProgramTerms: true,
    wantsEmailOffers: true,
    createdAt: "2026-04-15T10:20:00.000Z",
  },
];
