import { BrasaLocation, BrasaPointsRegistration, MenuItem, OperationsLocation, SaleTransaction, WasteRecord } from "./types";

export const SAMPLE_LOCATIONS: BrasaLocation[] = [
  { id: "COL-MED-POBLADO", name: "Brasaland El Poblado", country: "Colombia", city: "Medellín" },
  { id: "COL-MED-LAURELES", name: "Brasaland Laureles", country: "Colombia", city: "Medellín" },
  { id: "COL-BOG-CHAPINERO", name: "Brasaland Chapinero", country: "Colombia", city: "Bogotá" },
  { id: "COL-CAL-GRANADA", name: "Brasaland Granada", country: "Colombia", city: "Cali" },
  { id: "USA-MIA-BRICKELL", name: "Brasaland Brickell", country: "United States", city: "Miami" },
  { id: "USA-ORL-DOWNTOWN", name: "Brasaland Downtown", country: "United States", city: "Orlando" },
];

export const SAMPLE_REGISTRATIONS: BrasaPointsRegistration[] = [
  {
    fullName: "Ana Diaz",
    email: "ana@example.com",
    phone: "+57 300 123 4567",
    country: "Colombia",
    city: "Medellín",
    favoriteBrasalandLocation: "Brasaland El Poblado",
    dietaryPreferences: ["No restrictions"],
    howDidYouFindUs: "Social media",
    dateOfBirth: "1995-05-10",
    acceptsProgramTerms: true,
    wantsEmailOffers: true,
    createdAt: "2026-04-10T12:00:00.000Z",
  },
  {
    fullName: "Miguel Fernandez",
    email: "miguel@example.com",
    phone: "+57 301 987 2456",
    country: "Colombia",
    city: "Bogotá",
    favoriteBrasalandLocation: "Brasaland Chapinero",
    dietaryPreferences: ["Gluten-free"],
    howDidYouFindUs: "Recommendation",
    dateOfBirth: "1989-01-18",
    acceptsProgramTerms: true,
    wantsEmailOffers: false,
    createdAt: "2026-04-11T09:30:00.000Z",
  },
  {
    fullName: "Lucia Salazar",
    email: "lucia@example.com",
    phone: "+57 315 765 4321",
    country: "Colombia",
    city: "Cali",
    favoriteBrasalandLocation: "Brasaland Granada",
    dietaryPreferences: ["Vegetarian"],
    howDidYouFindUs: "Internet search",
    dateOfBirth: "1998-08-22",
    acceptsProgramTerms: true,
    wantsEmailOffers: true,
    createdAt: "2026-04-12T14:15:00.000Z",
  },
  {
    fullName: "Beth Carter",
    email: "beth@example.com",
    phone: "+1 305 123 4567",
    country: "United States",
    city: "Miami",
    favoriteBrasalandLocation: "Brasaland Brickell",
    dietaryPreferences: ["No restrictions", "Other"],
    howDidYouFindUs: "Walked by",
    dateOfBirth: "1990-08-03",
    acceptsProgramTerms: true,
    wantsEmailOffers: false,
    createdAt: "2026-04-13T11:05:00.000Z",
  },
  {
    fullName: "Marcus Lewis",
    email: "marcus@example.com",
    phone: "+1 407 444 2200",
    country: "United States",
    city: "Orlando",
    favoriteBrasalandLocation: "Brasaland Downtown",
    dietaryPreferences: ["No restrictions"],
    howDidYouFindUs: "Social media",
    dateOfBirth: "1992-04-06",
    acceptsProgramTerms: true,
    wantsEmailOffers: true,
    createdAt: "2026-04-14T16:45:00.000Z",
  },
  {
    fullName: "Daniela Torres",
    email: "daniela@example.com",
    phone: "+57 304 882 1901",
    country: "Colombia",
    city: "Medellín",
    favoriteBrasalandLocation: "Brasaland Laureles",
    dietaryPreferences: ["No restrictions"],
    howDidYouFindUs: "Recommendation",
    dateOfBirth: "1997-12-01",
    acceptsProgramTerms: true,
    wantsEmailOffers: true,
    createdAt: "2026-04-15T10:20:00.000Z",
  },
];

export const SAMPLE_MENU_ITEMS: MenuItem[] = [
  {
    id: "ITEM-PICANHA-250",
    name: "Picanha 250g",
    category: "Meat",
    basePrice: { USD: 18.5, COP: 74000 },
    ingredientCost: { USD: 7.2, COP: 28800 },
    prepTimeMinutes: 15,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-FRIES",
    name: "French Fries",
    category: "Side",
    basePrice: { USD: 4.5, COP: 18000 },
    ingredientCost: { USD: 1.2, COP: 4800 },
    prepTimeMinutes: 8,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
  {
    id: "ITEM-COKE",
    name: "Coca-Cola",
    category: "Beverage",
    basePrice: { USD: 2.5, COP: 10000 },
    ingredientCost: { USD: 0.8, COP: 3200 },
    prepTimeMinutes: 2,
    isAvailableInColombia: true,
    isAvailableInUSA: true,
    allergens: [],
    status: "Active",
  },
];

export const SAMPLE_OPERATIONS_LOCATIONS: OperationsLocation[] = [
  {
    id: "LOC-MEDELLIN-01",
    name: "Brasaland Medellin Centro",
    city: "Medellin",
    country: "Colombia",
    openingYear: 2008,
    seatingCapacity: 80,
    staffCount: 12,
    monthlyRentCost: { USD: 1500, COP: 6000000 },
    averageMonthlyUtilities: { USD: 400, COP: 1600000 },
    manager: "Carlos Jimenez",
    status: "Active",
  },
  {
    id: "LOC-MIAMI-01",
    name: "Brasaland Miami Beach",
    city: "Miami",
    country: "USA",
    openingYear: 2018,
    seatingCapacity: 100,
    staffCount: 15,
    monthlyRentCost: { USD: 5500, COP: 22000000 },
    averageMonthlyUtilities: { USD: 800, COP: 3200000 },
    manager: "Jake Morrison",
    status: "Active",
  },
];

export const SAMPLE_SALES: SaleTransaction[] = [
  {
    id: "TXN-2026-15482",
    locationId: "LOC-MEDELLIN-01",
    itemId: "ITEM-PICANHA-250",
    quantity: 2,
    totalPrice: { USD: 37.0, COP: 148000 },
    paymentMethod: "Credit card",
    timestamp: new Date("2026-04-15T19:30:00Z"),
    waiterName: "Maria Gonzalez",
  },
  {
    id: "TXN-2026-15483",
    locationId: "LOC-MIAMI-01",
    itemId: "ITEM-FRIES",
    quantity: 3,
    totalPrice: { USD: 13.5, COP: 54000 },
    paymentMethod: "Cash",
    timestamp: new Date("2026-04-15T20:15:00Z"),
    waiterName: "John Smith",
  },
  {
    id: "TXN-2026-15484",
    locationId: "LOC-MIAMI-01",
    itemId: "ITEM-COKE",
    quantity: 4,
    totalPrice: { USD: 10, COP: 40000 },
    paymentMethod: "Digital wallet",
    timestamp: new Date("2026-04-15T21:05:00Z"),
    waiterName: "Mia Wallace",
  },
];

export const SAMPLE_WASTE: WasteRecord[] = [
  {
    id: "WASTE-01",
    locationId: "LOC-MEDELLIN-01",
    itemId: "ITEM-FRIES",
    quantity: 1,
    reason: "Cooking error",
    cost: { USD: 1.2, COP: 4800 },
    timestamp: new Date("2026-04-15T13:10:00Z"),
    reportedBy: "Luis",
  },
  {
    id: "WASTE-02",
    locationId: "LOC-MIAMI-01",
    itemId: "ITEM-PICANHA-250",
    quantity: 1,
    reason: "Expired",
    cost: { USD: 7.2, COP: 28800 },
    timestamp: new Date("2026-04-15T14:00:00Z"),
    reportedBy: "Anna",
  },
];
